%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 613.273638
Camera.fy: 611.897782
Camera.cx: 321.819255
Camera.cy: 251.802312

# Camera distortion parameters (OpenCV)
Camera.k1: 0.081516
Camera.k2: -0.125375
Camera.p1: 0.005576
Camera.p2: -0.006738
Camera.k3: 0.0

Camera.width: 640
Camera.height: 480

# IR projector baseline times fx (aprox.)
Camera.bf: 49.833290

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 10.0

# Deptmap values factor
DepthMapFactor: 1.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7
